set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(AARCH EQUAL 32)
    set(PREFIX arm-none-eabi-)
else()
    set(PREFIX aarch64-none-elf-)
endif()

set(CMAKE_C_COMPILER ${PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${PREFIX}g++)
set(CMAKE_ASM_COMPILER  ${PREFIX}gcc)
set(CMAKE_AR ${PREFIX}ar)
set(CMAKE_OBJCOPY ${PREFIX}objcopy)
set(CMAKE_OBJDUMP ${PREFIX}objdump)
set(SIZE ${PREFIX}size)
